### ISSUE TITLE
Trying to match groups on initial migration

### ISSUE THREAD

**Issue by sklirg** [dotKom/feedme#53]
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 165, in handle
    emit_post_migrate_signal(created_models, self.verbosity, self.interactive, connection.alias)
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/django/core/management/sql.py", line 276, in emit_post_migrate_signal
    db=db)
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/guardian/management/__init__.py", line 39, in create_anonymous_user
    user.save()
  File "/vagrant/apps/authentication/models.py", line 194, in save
    super(OnlineUser, self).save(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/django/db/models/base.py", line 626, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/watson/registration.py", line 472, in _post_save_receiver
    self.update_obj_index(instance)
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/watson/registration.py", line 463, in update_obj_index
    _bulk_save_search_entries(list(self._update_obj_index_iter(obj)))
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/watson/registration.py", line 442, in _update_obj_index_iter
    "url": adapter.get_url(obj),
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/watson/registration.py", line 132, in get_url
    return obj.get_absolute_url()
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/django/db/models/__init__.py", line 40, in inner
    return reverse(bits[0], None, *bits[1:3])
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 551, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 415, in _reverse_with_prefix
    self._populate()
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 269, in _populate
    for pattern in reversed(self.url_patterns):
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/vagrant/onlineweb4/urls.py", line 129, in <module>
    urlpatterns += patterns('', url(r'^feedme/', include('feedme.urls', namespace='feedme')))
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 28, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/feedme/urls.py", line 3, in <module>
    from feedme.views import OrderlineDetail
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/feedme/views.py", line 30, in <module>
    groups = get_feedme_groups()
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/feedme/utils.py", line 6, in get_feedme_groups
    groups = [Group.objects.get(pk=i) for i in group_ids]
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/onlineweb/local/lib/python2.7/site-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
django.contrib.auth.models.DoesNotExist: Group matching query does not exist.
```

**Comment by sklirg** [comment]
Temporary fix: Make sure the groups specified in `settings.FEEDME_GROUPS` actually exists. Or empty the list.
